ERROR - 2021-03-13 07:45:07 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-03-13 07:45:07 --> Unable to connect to the database.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Controllers/AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#12 {main}
ERROR - 2021-03-13 07:48:01 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-03-13 07:48:01 --> Unable to connect to the database.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Controllers/AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#12 {main}
ERROR - 2021-03-13 08:38:58 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-03-13 08:38:58 --> Unable to connect to the database.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Controllers/AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#12 {main}
ERROR - 2021-03-13 08:38:58 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-03-13 08:38:58 --> Unable to connect to the database.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Controllers/AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#12 {main}
ERROR - 2021-03-13 09:01:18 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-03-13 09:01:18 --> Unable to connect to the database.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Controllers/AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#12 {main}
ERROR - 2021-03-13 09:02:17 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-03-13 09:02:17 --> Unable to connect to the database.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Controllers/AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#12 {main}
ERROR - 2021-03-13 09:04:27 --> Error connecting to the database: No such file or directory
CRITICAL - 2021-03-13 09:04:27 --> Unable to connect to the database.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#3 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/BaseModel.php(624): CodeIgniter\Model->doFirst()
#4 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(156): CodeIgniter\BaseModel->first()
#5 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(20): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#6 /storage/emulated/0/htdocs/sid/vendor/myth/auth/src/Controllers/AuthController.php(85): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#7 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(936): Myth\Auth\Controllers\AuthController->attemptLogin()
#8 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#11 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#12 {main}
CRITICAL - 2021-03-13 22:08:30 --> You do not have sufficient permissions to access that page.
#0 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Filters/Filters.php(181): Myth\Auth\Filters\RoleFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), Array)
#1 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(403): CodeIgniter\Filters\Filters->run('admin', 'before')
#2 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /storage/emulated/0/htdocs/sid/public/index.php(44): CodeIgniter\CodeIgniter->run()
#4 /storage/emulated/0/htdocs/sid/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(45): require_once('/storage/emulat...')
#5 {main}
CRITICAL - 2021-03-13 18:13:22 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(159): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:14:37 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(159): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:17:08 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:18:13 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(170): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:19:12 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:22:49 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:28:41 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:29:56 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:32:45 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:36:39 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:40:15 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:43:53 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(53): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:45:06 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(43): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 18:46:49 --> Call to undefined function CodeIgniter\locale_set_default()
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\bootstrap.php(148): CodeIgniter\CodeIgniter->initialize()
#1 C:\Users\dell\sid\spark(43): require('C:\\Users\\dell\\s...')
#2 {main}
CRITICAL - 2021-03-13 12:19:31 --> Trying to get property 'username' of non-object
#0 C:\Users\dell\sid\app\Views\layout\header.php(21): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\Users\\dell\\s...', 21, Array)
#1 C:\Users\dell\sid\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\Users\\dell\\s...')
#2 C:\Users\dell\sid\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\Users\dell\sid\vendor\codeigniter4\framework\system\View\View.php(468): CodeIgniter\View\View->render('layout/header', NULL, true)
#4 C:\Users\dell\sid\app\Views\admin\template.php(11): CodeIgniter\View\View->include('layout/header')
#5 C:\Users\dell\sid\vendor\codeigniter4\framework\system\View\View.php(220): include('C:\\Users\\dell\\s...')
#6 C:\Users\dell\sid\vendor\codeigniter4\framework\system\View\View.php(222): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 C:\Users\dell\sid\vendor\codeigniter4\framework\system\View\View.php(236): CodeIgniter\View\View->render('admin/template', Array, true)
#8 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('admin/index', Array, true)
#9 C:\Users\dell\sid\app\Controllers\Admin.php(70): view('admin/index', Array)
#10 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(878): App\Controllers\Admin->index()
#11 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(413): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#12 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(324): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\Users\dell\sid\public\index.php(44): CodeIgniter\CodeIgniter->run()
#14 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\dell\\s...')
#15 {main}
CRITICAL - 2021-03-13 14:12:34 --> Too few arguments to function App\Controllers\Manage::newrecord(), 0 passed in C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php on line 878 and exactly 1 expected
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(878): App\Controllers\Manage->newrecord()
#1 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(413): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Manage))
#2 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(324): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\Users\dell\sid\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\dell\\s...')
#5 {main}
CRITICAL - 2021-03-13 14:13:13 --> Too few arguments to function App\Controllers\Manage::newrecord(), 0 passed in C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php on line 878 and exactly 1 expected
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(878): App\Controllers\Manage->newrecord()
#1 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(413): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Manage))
#2 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(324): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\Users\dell\sid\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\dell\\s...')
#5 {main}
CRITICAL - 2021-03-13 14:53:49 --> Too few arguments to function App\Controllers\Manage::newrecord(), 0 passed in C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php on line 878 and exactly 1 expected
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(878): App\Controllers\Manage->newrecord()
#1 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(413): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Manage))
#2 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(324): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\Users\dell\sid\public\index.php(44): CodeIgniter\CodeIgniter->run()
#4 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\dell\\s...')
#5 {main}
CRITICAL - 2021-03-13 15:00:10 --> syntax error, unexpected '1' (T_LNUMBER), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(265): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\Users\\dell\\s...')
#1 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Autoloader\Autoloader.php(228): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#3 [internal function]: spl_autoload_call('App\\Controllers...')
#4 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(839): class_exists('\\App\\Controller...', true)
#5 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->startController()
#6 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(324): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\dell\sid\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\dell\\s...')
#9 {main}
CRITICAL - 2021-03-13 15:09:17 --> Class 'Locale' not found
#0 C:\Users\dell\sid\vendor\codeigniter4\framework\system\I18n\Time.php(146): CodeIgniter\I18n\Time->__construct('2021-03-02 20:5...', NULL, NULL)
#1 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Entity.php(518): CodeIgniter\I18n\Time::parse('2021-03-02 20:5...')
#2 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Entity.php(313): CodeIgniter\Entity->mutateDate('2021-03-02 20:5...')
#3 C:\Users\dell\sid\app\Controllers\Manage.php(37): CodeIgniter\Entity->__get('created_at')
#4 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(878): App\Controllers\Manage->index()
#5 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(413): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Manage))
#6 C:\Users\dell\sid\vendor\codeigniter4\framework\system\CodeIgniter.php(324): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\Users\dell\sid\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 C:\Users\dell\sid\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\Users\\dell\\s...')
#9 {main}
